###
POST http://localhost:3001/api/Train/
Content-Type: application/json

{
    "people": ["divya_patel", "hackerbhaiya"],
    "userId": "612b189cd7a39df66e53a502"
}
###
GET http://localhost:3001/api/Train/

###
GET http://localhost:3001/api/Visualize/

###
POST http://localhost:3001/api/Visualize/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml0c215bGlmZTFAZ21haWwuY29tIiwiaWQiOiI2MTJjNmJhZTliMzNiNDcwOTQxODRjYWIiLCJpYXQiOjE2MzAzOTA0MzMsImV4cCI6MTYzMDM5NDAzM30.Ho4k-8jSTC_N1fIk0c6bpclC5SdPLPqgXnuGWbmUQtE

{
    "div": 2,
    "rating": 1300,
    "topic": ["hello"],
    "time": "4",
    "userId": "612c6bae9b33b47094184cab"
}
###
POST http://localhost:3001/api/Users/signup
Content-Type: application/json

{
    "username": "itsmylife0",
    "name": "itsmylife",
    "firstname": "itsmylife",
    "email": "itsmylife1@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}
###
POST http://localhost:3001/api/Users/signin
Content-Type: application/json

{
    "email": "itsmylife1@gmail.com",
    "password": "123"
}
###
POST http://localhost:3001/api/Users/register
Content-Type: application/json

{
     "name": "Shreenanda P",
    "email": "shreenandap@gmail.com",
    "password": "adminhubhai@isroscientist"
}

###
POST http://localhost:3001/api/Users/activateEmail
Content-Type: application/json

{
"activation_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hyZWVuYW5kYSBQIiwiZW1haWwiOiJzaHJlZW5hbmRhcEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMiR5cXg2bW81LklUOUtpeVA0MlVSZUEuY0ouV3pJenFiNGlGQkhvNDljM2ZuMXlJamJWbDFmRyIsImlhdCI6MTYzMDQxMjk4MiwiZXhwIjoxNjMwNDEzMjgyfQ.sC9b1V5Oe4a2jAsdX6nTGtRESTGyqBhx_oap_cMLr30"
}
###
GET http://localhost:3001/api/Users/

###
POST http://localhost:3001/api/Users/register
Content-Type: application/json

{
    "name": "S",
    "email": "xyz@gmail.com",
    "password": "1234"
}
###
POST http://localhost:3001/api/Users/login
Content-Type: application/json

{
   "email": "shreenandap@gmail.com",
   "password": "adminhubhai@isroscientist"
}
###
POST http://localhost:3001/api/Users/getAccessToken